# Book settings
title                       : A-Ro-Ma-Math  # The title of the book. Will be placed in the left navbar.
author                      : Robert Mařík  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  
# Information about where the book exists on the web
repository:
  url                       : https://github.com/robert-marik/aromamath  # Online location of your book
  branch                    : main  # Which branch of the repository should be used when creating links (optional)


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    #- dollarmath